ThrowTheSwitch/Ceedling

- lib/ceedling/defaults.rb
On my system the build process failed because i had a space in the expanded path which are inserted by ceedling. I was using a custom test_compiler & linker, but not overriding the preprocessor.
> Fixing: Default preprocessor failing due to space in expanded path.

- plugins/module_generator/lib/module_generator.rb
Cause: The usage of regex's special characters in MODULE_GENERATOR_SOURCE_ROOT, MODULE_GENERATOR_PROJECT_ROOT or MODULE_GENERATOR_TEST_ROOT.
Example: For example when MODULE_GENERATOR_SOURCE_ROOT equals "../" and try to create a module with folders in the path (like "folderName/source.c") then the first two letters of the path will be missing in the generated file (like "lderName/test_source.c").
Solution: The solution is to escape those strings (with Regexp.escape()) before using them to compose the final regex passed as argument for the method String.sub().
> Bug in the module_generator.

- plugins/xml_tests_report/xml_tests_report.rb
The last commit that claimed to have fixed the botched XML, in fact didn't. This does, and makes it more consistent with the structure of the rest of the document...
> Fixed XML inside <FailedTests>

- docs/CeedlingPacket.md
There was an issue with the code block for the sample rakefile that caused the ruby comment (starting with a #) to appear as an H1 instead of as just a code comment.  This simply wrapped the code with the ```ruby markdown syntax.
> Fixes formatting issue with sample rakefile

- lib/ceedling/rules_cmock.rake
Fixes #77 
Not perfect yet. The pattern should probably use a system-dependent file separator, rather than just forward- and back-slash
Also, I'm not positive where the correct place to add a test for this functionality is.
> rake task pattern only looks for mock prefix in file basename

- .gitmodules
When enabled, this plug-in replaces CMock with the [Fake Function Framework](https://github.com/meekrosoft/fff) for auto-mock generation.
fff works a little differently than CMock, and gives you some different (less-strict) mocking options. This plug-in also includes a few additional "Unity-style" TEST_ASSERT_ macros for use in tests. You can see some examples in the the [readme](https://github.com/ElectronVector/fake_function_framework/blob/master/README.md).
The mock generator uses the CMock header parsing stuff, and so can still use some of the CMock config options.
This does include the [fff repository](https://github.com/meekrosoft/fff) as a submodule.
The default `rake` task runs the rspec tests and all the tests for the included example.
> Added a plug-in to use the Fake Function Framework for mocking

- .travis.yml
- Gemfile
- ceedling.gemspec
In versions of Ruby above 2.1.0, curses is not built in but a gem instead. I've added the dependency and updated the ci to test the newer versions of ruby on builds.
> curses gem dependence 

- lib/ceedling/generator_test_runner.rb
As @matt21121 pointed out in #85, currently parametrized tests doesn't work with Ceedling.
Because I definitely want to use this option, I implemented the way he explained in the issue.
The modification is very simple.
I just use find_tests provided by UnityTestRunnerGenerator class instead of embedded one.
You can enable the feature by enabling "use_param_tests" option to project.yml.
But this modification has an issue.
Because Ceedling uses cmock option to initialize UnityTestRunnerGenerator,
we have to specify the parameter under cmock as below.
```yaml
:cmock:
:use_param_tests: true
```
I think this is strange. So, I'll modify this issue in another pull-request.
> use UnityTestRunnerGenerator to find test cases

- lib/ceedling/configurator.rb
- lib/ceedling/setupinator.rb
As I mentioned in #97, Ceedling uses cmock option to initialize UnityTestRunnerGenerator,
Because get_runner_config method is only used by the initialization, it shall have unity option.
That is why, I separated unity config from cmock config and let get_runner_config return unity config.
By merging this request, you can speicfy "use_param_tests" under "unity" instead of cmock as below.
```yaml
:unity:
:use_param_tests: true
```
> separate unity config and cmock config

- bin/ceedling
When not using PTY or Popen4, we just capture the output after everything is done.
However, we need to return the captured `stdout` as a `StringIO` (instead of a `String`) so the block can use `each` to iterate over it.
Fixes #84
> Fixed error when not using PTY or Popen4 (like on Windows).

- lib/ceedling/configurator_validator.rb
- lib/ceedling/constants.rb
This change makes Ceedling a little better at handling errors due to users deleting a directory that Ceedling needs, Let's say you are cleaning a repository and you get rid of the `build` directory. Currently, Ceedling does the following:
```
dom@osboxes:~/dev/test-project$ rm -rf build/
dom@osboxes:~/dev/test-project$ rake test:all
ERROR: Config filepath [:project][:build_root]['build'] does not exist on disk.
rake aborted!
/home/dom/dev/test-project/vendor/ceedling/lib/ceedling/configurator.rb:271:in `validate'
/home/dom/dev/test-project/vendor/ceedling/lib/ceedling/setupinator.rb:31:in `do_setup'
vendor/ceedling/lib/../lib/ceedling/rakefile.rb:46:in `<top (required)>'
vendor/ceedling/lib/ceedling.rb:66:in `load'
vendor/ceedling/lib/ceedling.rb:66:in `load_project' …
```
> Made Ceedling more graceful when encountering a missing directory that it generates.

- docs/CeedlingPacket.md
The :tools: blurb used typographical quotes, which were accepted by Ruby but caused bad command lines.   
Additionally, it used an unexisting COLLECTION_TEST_DEFINES.  
Finally, there were stray text formatting commands.
I would suggest breaking down this whole document into smaller pages, each with its own focus. Or even turning it into a GitHub wiki.
> Fixes to the :tools: YAML blurb, plus formatting

- lib/ceedling/defaults.rb
Add a CEEDLING_PLUGINS array which defaults to containing Ceedling's own plugin path but can be added to by project.yml. This means that the plugins/load_paths section can be omitted if only the Ceedling-provided plugins are being used.
We don't copy Ceedling into our project repositories, so this saves the project configuration file from having to know where Ceedling is installed, or doing something ugly like
```
:plugins:
:load_paths:
- "#{PROJECT_CEEDLING_ROOT}/plugins"
```
> Plugin paths

- lib/ceedling/constants.rb
Suppresses empty TEST OUTPUT sections, e.g.
```
-----------
TEST OUTPUT
-----------
[test_foo.c]
- ""
```
> Swallow extra blank line in Unity output

- lib/ceedling/rakefile.rb
This restores the exit code returning error on failing tests. There is also an added option that can be put in the project.yml. If setting `:graceful_fail:  true` in project.yml, it will behave the same way it currently does.
As mentioned in #117, the default behavior is for it to return error on failing tests as all test suits do this for CI and scripting purposes.
> Restored error code on tests failing and added option to gracefully fail

- lib/ceedling/tasks_base.rake
Slight oversight in my earlier patch - can't load `rules_release.rake` if there's no release build.
> Only load release rules if there is a release build

- lib/ceedling/configurator.rb
- lib/ceedling/project_config_manager.rb
- lib/ceedling/setupinator.rb
We use a *lot* of options files to configure our products.
In some cases it would be really nice to be able to have config files (project.yml, options files) load other config files, for commonly re-used definitions (target processor, common code modules, etc).
This patch makes that possible, for example:
```
---
:include:
- path/to/config.yml
- path/to/another/config.yml
...
```
These can be recursively nested, the included files can include other files in turn, just like in C.
> Config file includes

- lib/ceedling/defaults.rb
- lib/ceedling/test_invoker.rb
I added new option "use_test_definition".
This can be defined under "defines" section as below.
``` yaml
:defines:
:use_test_definition: true
```
The default value is false.
If you specify this option, you can append -DTEST_FILE_NAME to the build option. 
This feature is discussed in following threads in detail.
- https://github.com/ThrowTheSwitch/Ceedling/issues/88
- https://github.com/TE-HiroakiYamazoe/Ceedling/pull/2
> add new option "use_test_definition"

- lib/ceedling/file_path_utils.rb
I have the same problem as described in issue #55.  I want to specify a path as being "./**".  I don't know why but currently a "./" prefix is intentionally removed.  This change no longer removes that prefix.
> Don't remove './' prefix

- lib/ceedling/file_path_utils.rb
PR #144 caused the `-:` and `+:` prefixes to be removed by `FilePathUtils.standardize` even if not followed by a `./`. This clobbered the ability to remove paths from the list in e.g. an options file.
I'm not sure what the original intent of this line was:
```
path.gsub!(/^((\+|-):)?\.\//, '')
```
as it removed both a leading `./` and any `-:` that preceded it. I think the right thing to do is to remove it altogether.
> Fix inability to remove paths, clobbered by #144

- lib/ceedling/release_invoker.rb
`EXTENSION_SUBPROJECTS` may not be defined, especially if not using the new subprojects plugin.
> Fix error when not using subprojects plugin

- lib/ceedling/configurator.rb
- lib/ceedling/configurator_builder.rb
- lib/ceedling/configurator_setup.rb
- lib/ceedling/dependinator.rb
CMock allows `unity_helper` to be an array of multiple header files. Allow the same in Ceedling.
> Allow multiple CMock Unity helpers

- assets/project_as_gem.yml
- assets/project_with_guts.yml
- plugins/gcov/config/defaults.yml
- plugins/gcov/gcov.rake
- plugins/gcov/lib/gcov.rb
- plugins/gcov/lib/gcov_constants.rb
This commits does some work on the gcov plugin most of which is clean up.
The two new things this commit does:
- Now puts the gcov coverage html report into artifacts  
- Adjust level of detail in the report by defining either 'basic' or 'advanced'
The new setting can be added to the project.yml as such:
```
:gcov:
:html_report_type: basic
```
or
```
:gcov:
:html_report_type: advanced
```
> Improve Gcov reports

- .gitignore
- .travis.yml
- examples/blinky/project.yml
- examples/temp_sensor/project.yml
- lib/ceedling/configurator.rb
- lib/ceedling/defaults.rb
Fixed issue seen in #166 and updated travis to create and destroy a module to confirm this behaviour is fixed. 
I will admit this is not the best solution. We need to be able to detect duplicate rake files in the configurator and not double load those rake files.
> Fixed double module create rake.

- lib/ceedling/defaults.rb
`:unity_helper` gets added to `:includes` which fails if `:includes` is not specified (undefined method `+` for `nil`).
Make `:includes` default to `[]`
> Add default empty array for cmock_includes

- assets/test_example_file_boom.c
- assets/test_example_file_success.c
- bin/ceedling
- spec/spec_system_helper.rb
- spec/system/deployment_spec.rb
This commit is designed to fix #148, #117, and #174. It also adds more system tests with altered exit statuses to confirm behaviour of failures and when to expect something to return failure. 
@mvandervoord  I see you made a commit to address this issue as well, so  if you have some spare time I'd like to discuss both commits and make sure they are compatible/make sense as a solution to the issue.
> Ceedling now returns the correct status and more spec test for verification.

- .travis.yml
- assets/project_with_guts_gcov.yml
- examples/temp_sensor/rakefile.rb
- plugins/gcov/gcov.rake
- spec/gcov/gcov_deployment_spec.rb
- spec/gcov/gcov_test_cases_spec.rb
This commit adds deployment testing for the gcov plugin and is a start to addressing #96. More fine grain testing is still needed, but this confirms the plugin works at the system level  via travis every commit.
> gcov deployment tests

- plugins/gcov/config/defaults.yml
This pull request addresses the following error on Windows 7 with italian localization when trying to generate gcovr html report.
```
C:\TestCeed28>rake utils:gcov
Creating a basic html report of gcov results in build/artifacts/gcov/GcovCoverag
eResults.html...
"build.*" non è riconosciuto come comando interno o esterno,
un programma eseguibile o un file batch.
ERROR: Shell command failed.
> Shell executed command:
'gcovr -p -b -e '^vendor.*|^build.*|^test.*|^lib.*' --html -r . -o  "build/artif
acts/gcov/GcovCoverageResults.html"'
> And exited with status: [255].
rake aborted!
ShellExecutionException: ShellExecutionException
```
On my system works well, but I'm not sure this is the best string escaping method...
> Add escaping in gcovr parameter

- lib/ceedling/configurator_builder.rb
- lib/ceedling/configurator_setup.rb
- lib/ceedling/file_finder.rb
- lib/ceedling/rules_release.rake
- lib/ceedling/rules_release_deep_dependencies.rake
Test support files are not meant to be included in the release build. This PR makes Ceedling stop including those files in the release build.
> Stop including test support files in release build

- docs/CeedlingPacket.md
- lib/ceedling/flaginator.rb
This PR adds support for regular expressions for 'per-file' flags instead of simple literals and 'anything else'.
The current system has two issues:
1. The configuration file can become long if many flags are added to specific files
2. On adding a new file it is easy to forget to add appropriate flags.
With regular expressions it is easy to add flags to different groups of files (tests, runners, mocks, modules, etc).
1. Literals
2. Regex matches
3. `.*` respectively `*`
```
:'(mock|test)_\w+?(?<!_runner)':  # match only mocks and test files
- -x c++
:'test_\w+?_runner':  # match only runners
- -Og
:'Sut_.+':
- -ansi
:'.*':   # match anything else, equivalent to :*:
- -O3
```
> Add support for regexes in per-file flags

- plugins/gcov/config/defaults.yml
The GCOV HTML detailed report does not generate an html file.
Added parameter for generating the proper html files.
Tested with gcovr 3.3
> Fixed gcvor detailed HTML report generation.

- .travis.yml
After looking at the last few pull requests, it seems the linux builds now need sudo to install gcovr via pip. I'm not sure what changed on Travis's side, but this change should fix that and we should try to retrigger the pull requests that failed due to this issue.
> sudo pip install for linux

- docs/CeedlingPacket.md
- plugins/module_generator/lib/module_generator.rb
- plugins/module_generator/module_generator.rake
- spec/spec_system_helper.rb
(see #201 for original but all info is copied here for convenience)
By default ceedling expects the following project structure:
- project_root
- src
- test
However, we are using ceedling in the following directory/project structure:
- project_root
- driver1
- src
- inc
- test
- driver2
- src
- inc
- test
Instead of having separate Ceedling projects for every driver, we wanted Ceedling to manage all the tests for all drivers. That way it was also easier to generate a complete code coverage report (since Ceedling had everything built-in to do so).
This worked out-of-the-box but the slightly annoying thing was that module:create/destroy did not work properly with this project structure.
So I added a way to create a module in a subdirectory of the project_root.
By specifying …
> Expand module:create/destroy to 'run' in subfolder (Enhancement of #201)

- assets/default_gitignore
- bin/ceedling
- spec/gcov/gcov_deployment_spec.rb
- spec/spec_system_helper.rb
- spec/system/deployment_spec.rb
This PR adds an option to Ceedling to generate a .gitignore file as sought out by #45. This PR also contains a little bit of spec clean up so the output of the rspec system tests isn't as sloppy as before.
> added with-ignore option to Ceedling new

- lib/ceedling/preprocessinator_extractor.rb
While playing around to see what ways Ceedling can be sped up, I found a quick change that can be done to preprocessinator_extractor.rb to help performance. The change replaces ".match" with "=~" for a noticeable performance increase when doing test:all (it was about 4% on my system).
I'm going to play with more things over the next few weeks so see if any thing else can be improved performance wise.
> Use "=~" instead of ".match" for better performance in preprocessinator_extractor.rb

- .travis.yml
While updating the docs for the gcov plugin, I noticed the OSX builds were not working in their current state. The issues were as followed:
- `pip` is not available out of the box any more on OSX, but you can use `pip2` or `pip3`(see https://github.com/travis-ci/travis-ci/issues/8829)
- The last two OSX Versions (10.11 and 10.12 see http://rubies.travis-ci.org/) do not have ruby 2.0.0 out of the box so I upped the minimum version to 2.1 and also the max to 2.4 (since that was released a while ago)
> Travis fixes for osx

- plugins/gcov/README.md
- plugins/gcov/gcov.rake
Adds more documentation to the gcov plugin in response to #224. This commit needs #225 to pass Travis (due to the OSX fixes).
> Added more documentation for the gcov plugin

- lib/ceedling/file_finder.rb
Minor change to improve scoping
> Move FileFinder semaphore out of global namespace

- examples/blinky/rakefile.rb
- lib/ceedling/configurator.rb
- lib/ceedling/configurator_plugins.rb
- lib/ceedling/defaults.rb
Fixes #262
Possible impacts:
In `ConfiguratorPlugins#add_load_paths` I've removed the lines
```
config[:plugins][:load_paths].each do |root|
@system_wrapper.add_load_path( root ) if ( not @file_wrapper.directory_listing( File.join( root, '*.rb' ) ).empty? )
```
which means that plugins of the form `path/to/plugin_dir/plugin.rb` will not work, but I think these are obsolete anyway as they would not have been found by `ConfiguratorPlugins#find_script_plugins` and therefore would have been flagged as invalid by `ConfiguratorSetup#validate_plugins`
In ConfiguratorPlugins#add_load_paths I've changed the contents of `plugin_paths` (that ultimately gets stored in `config[:plugins][(plugin + '_path').to_sym]` by `Configurator#find_and_merge_plugins` to no longer include the trailing `lib` …
> Plugin path fixes

- lib/ceedling/generator_test_results.rb
- lib/ceedling/plugin_manager.rb
- lib/ceedling/plugin_reportinator.rb
- lib/ceedling/plugin_reportinator_helper.rb
- lib/ceedling/tool_executor.rb
- plugins/junit_tests_report/lib/junit_tests_report.rb
- spec/generator_test_results_spec.rb
- spec/support/test_example.fail
- spec/support/test_example_empty.pass
- spec/support/test_example_ignore.pass
- spec/support/test_example_mangled.pass
- spec/support/test_example_with_time.pass
This PR adds a simple timing mechanism to Ceedling via benchmark and updates the junit plugin to take advantage of this improvement. 
I'm aware of the commit in unity to time individual tests (https://github.com/ThrowTheSwitch/Unity/pull/278), which can eventually replace the benchmark inside Ceedling.
> Timing for junit

- docs/CeedlingPacket.md
Addition per #229, #146 and #116, as I couldn't see this in the documentation.
Unfortunately I have only Pandoc and MS Word available for editing ODT and PDF. Both Word and Pandoc introduce unrequired changes into the documents. If someone else is able to either convert the markdown to these two formats or otherwise edit the file to add the change that would be great!
> Note MS Windows file name restrictions

- lib/ceedling/file_wrapper.rb
- lib/ceedling/test_invoker.rb
I have managed to re-define the needed defines and project settings.
This is performed only when there are specific test defines have some defines.
This is a RFC, maybe there is a better way to redo the re-definition of the needed pre-processor options, but this works.
> Preprocessing options for specific tests

- docs/CeedlingPacket.md
- lib/ceedling/defaults.rb
- lib/ceedling/dependinator.rb
- lib/ceedling/file_path_utils.rb
- lib/ceedling/generator.rb
- lib/ceedling/release_invoker_helper.rb
- lib/ceedling/rules_release.rake
- lib/ceedling/rules_tests.rake
- lib/ceedling/test_invoker_helper.rb
If the compiler can generate dependencies as a side-effect of compilation (e.g. gcc's -MMD option) then there is no need for a separate call to gcc to generate the dependency files. Add a new project option `generate_deep_dependencies` which can be set to false to skip this step, and add a ${4} parameter to `generate_object_file` to pass in the path to the output dependency file.
> Allow the separate dependency generation step to be skipped

- plugins/gcov/config/defaults.yml
- plugins/gcov/gcov.rake
- plugins/gcov/lib/gcov.rb
- plugins/gcov/lib/gcov_constants.rb
This PR is PR #261 cleaned up. The issue with the tests were if the filter was not defined, the gcovr command would never be run. The solution was to just use the default if the filter was not defined.
> Gcov filter fixes (cleanup of  Added option to personalize the gcovr report filter.)

- spec/gcov/gcov_test_cases_spec.rb
- spec/spec_system_helper.rb
- spec/system/deployment_spec.rb
This PR cleans up the output on some of the deploy spec tests that did not pip STDERR to STROUT. While doing this, I also noticed several of the module create deployment tests were never called so I added them to the appropriate deployment tests.
> Spec output cleanup & made sure all deploy tests were called correctly.

- lib/ceedling/plugin_manager.rb
This fixes ceedling calling plugins with methods they don't support by checking if they respond to the method first. When doing other clean up, I noticed this error was occurring on `post_error` for the `StdoutPrettyTestsReport` plugin.
```
Traceback (most recent call last):
4: from vendor/ceedling/lib/../lib/ceedling/rakefile.rb:84:in `block in <top (required)>'
3: from /tmp/d20180607-6210-1ceqetp/fake_project/vendor/ceedling/lib/ceedling/plugin_manager.rb:86:in `post_error'
2: from /tmp/d20180607-6210-1ceqetp/fake_project/vendor/ceedling/lib/ceedling/plugin_manager.rb:97:in `execute_plugins'
1: from /tmp/d20180607-6210-1ceqetp/fake_project/vendor/ceedling/lib/ceedling/plugin_manager.rb:97:in `each'
/tmp/d20180607-6210-1ceqetp/fake_project/vendor/ceedling/lib/ceedling/plugin_manager.rb:99 …
```
> Only call plugin if it responds to the given method

- assets/project_with_guts.yml
- assets/test_example_file_verbose.c
- plugins/raw_output_report/lib/raw_output_report.rb
- spec/spec_system_helper.rb
- spec/system/deployment_spec.rb
This pull request add a raw output plugin as described in #252. For each test it will include an individual logging output in the artifacts directory. So if you had tests `test_foo.c` and `test_bar.c` the test artifacts directory would contain `test_foo.log` and `test_bar.log`.
> Feature #252: raw output plugin

- lib/ceedling/preprocessinator_includes_handler.rb
- spec/preprocessinator_includes_handler_spec.rb
I've been working with a new client and one of the files in their repo generated the following error:
> 
> rake aborted!
> ArgumentError: invalid byte sequence in UTF-8
> /home/dom/.rvm/gems/ruby-2.5.1/gems/ceedling-0.28.2/lib/ceedling/preprocessinator_includes_handler.rb:33:in `gsub!'
After some investigating, I found ruby can scrub a string before trying process it with gsub. The error is now gone without changing the source file.
> Scrub file in preprocessinator if it's not a valid incoding

- lib/ceedling/configurator.rb
- lib/ceedling/generator.rb
- lib/ceedling/rules_tests.rake
- lib/ceedling/test_invoker.rb
It appeared that the libraries configuration section was never used, at least when linking tests.
> Use the libraries section in the YAML file when doing tests

- plugins/junit_tests_report/lib/junit_tests_report.rb
Follow up to testing https://github.com/ThrowTheSwitch/Unity/pull/380. Unity works fine, but the junit xml generation was broken from the extra double quotes. This just scrubs and replaces double quotes with their encoded version.
> Make junit escape strings in test names

- plugins/gcov/config/defaults.yml
- plugins/gcov/lib/gcov.rb
Fixes #293. What ended up happening was the `collection_defines_test_and_vendor` in gcov would take precedence over the completely merged version of `collection_defines_test_and_vendor`. This fix moves the default define to the default config and just lets the rest of ceedling set up `collection_defines_test_and_vendor`.
> Don't clobber the collected defines in gcov

- .travis.yml
This pull requests does two things. First it adds ruby 2.6 to the ram matrix to test feeling out against the latest ruby release.  The second thing this does is raise the minimum ruby tested to 2.3. Travis recently started having bundler errors on their OSX for ruby 2.1 and 2.2 as seen on one of the recent pull requests here and have also both reached their end of life a while ago.
> Add ruby-2.6 to travis and raise minimum ruby to 2.3

- assets/project_as_gem.yml
- assets/project_with_guts.yml
- assets/project_with_guts_gcov.yml
- plugins/gcov/README.md
- plugins/gcov/config/defaults.yml
- plugins/gcov/gcov.rake
- plugins/gcov/lib/gcov_constants.rb
Adds a new feature for #331. Now the gcov options support both enabling an xml report and enabling an xml report separately. 
```
:gcov:
:html_report: TRUE
:html_report_type: basic
:xml_report: TRUE
```
If not supplied, all of the options above will have safe defaults (both reports enabled and basic html report type).
> Add xml report option to utils:gcov

- plugins/junit_tests_report/README.md
- plugins/junit_tests_report/lib/junit_tests_report.rb
- plugins/xml_tests_report/README.md
- plugins/xml_tests_report/lib/xml_tests_report.rb
#323
If configuration tokens are not used, behavior isn't modified.
Otherwise, this makes it possible to change the output file of junit_tests_report or/and xml_tests_report plugins.
> Add two configuration tokens to configure output file name for junit_tests_report and xml_tests_report plugins.

- plugins/gcov/lib/gcov.rb
This helps to address part of #329. It does not try to mess with overall coverage results, but will now explicitly state when there are no results for a file.
> Explicitly state in gcov when there are no coverage results for a file

- bin/ceedling
While testing other fixes, I realized the --local option was missing `vendor/ceedling/bin` which made the ceedling bash script at the base of the project unusable. I also added chmods to mark the copied  executables for ease of use.
> Copy binary for local and chmod for consistency

- assets/default_gitignore
Noticed the path to logs wasn't right. I just verified on my end that the logs directory got generated at `build/logs` and not `buildd/logs`
> Update default_gitignore with correct path to logs

- lib/ceedling/tasks_tests.rake
- spec/spec_system_helper.rb
- spec/system/deployment_spec.rb
This fixes #280 by directly invoking test:all when test is presented to make sure all hooks are triggered. Other plugins may need to follow suit if similar rake tasks are set up like this one.
> Directly invoke test:all in test alias

- .gitignore
- plugins/gcov/lib/gcov_constants.rb
If you use local copy of Ceedling (--local argument), by default in the
GCov html report the local copy of the vendored Ceedling files are also
covered (unity.h, ...)
This change excludes the local Ceedling/vendor directory from the report.
> Exclude local copy of Ceedling vendor dir in GCov

- docs/CeedlingPacket.md
A hyphen at the beginning of a line is interpreted as the bullet list by GitHub markdown parser.
> Fix formatting of the docs

- lib/ceedling/test_invoker.rb
Keys in project_config_hash are stored as a downcase names, therefore specific test definitions for test with uppercase names cannot be found (like for temp_sensor test names).
To fix it test definition is adjusted to match project_config_hash key.
> Downcase test names for specific test definitions

- plugins/junit_tests_report/lib/junit_tests_report.rb
Added XML special character substitution to the JUnit report plugin so that special characters in stdout do not cause malformed XML.
> Safe JUnit XML report generation

- bin/ceedling
- spec/spec_system_helper.rb
This attempts to alleviate some of the issues brought up in #182 by adding an empty file that can be added via git.
> Generate deleteme file in test/support to make it easier to use ceedling out of the box with git

- lib/ceedling/cacheinator.rb
- lib/ceedling/cacheinator_helper.rb
- lib/ceedling/constants.rb
- lib/ceedling/dependinator.rb
- lib/ceedling/objects.yml
- lib/ceedling/project_config_manager.rb
- lib/ceedling/rules_tests.rake
- lib/ceedling/task_invoker.rb
- lib/ceedling/test_invoker.rb
This PR helps to solve issue #369.
Preprocessor definitions for specific tests can be set in project.yml file.
Recompilation is needed when the same files are used for tests with changed definitions to avoid test failure caused by using by ceedling object files created in former compilation. To do this special file defines_dependency.yml in cache directory is created. This file contains dependencies between source files and the preprocessor definitions from the project.yml. Changing the definitions for file used in the current test compilation forcing recompilation for all sources. Rake rules are enhanced with force_build file with new timestamp. Tasks must be reenabled to correctly call dependent rake tasks.
Examples to demonstrate issue can be found here: …
> Recompilation after change preprocessor definitions for specific tests

- docs/CeedlingPacket.md
- lib/ceedling/task_invoker.rb
- lib/ceedling/test_invoker.rb
This PR is for the issue #402.
Introduce a new task, `build_only` for building only the tests, not running them.
> Introduce the task build_only for tests

- lib/ceedling/generator_test_results.rb
- plugins/junit_tests_report/lib/junit_tests_report.rb
- spec/spec_system_helper.rb
- spec/support/test_example.fail
- spec/support/test_example.pass
- spec/support/test_example_ignore.pass
- spec/support/test_example_mangled.pass
- spec/support/test_example_with_time.pass
- spec/system/deployment_spec.rb
This PR makes use of the test time functions in unity and makes it so the base usecases of Ceedling will work with it. 
Currently if UNITY_INCLUDE_EXEC_TIME is defined, the Ceedling sanity check will fail. After this PR, the sanity check will pass and the junit plugin will take advantage of the new outputs.
> utilize unity time results

- plugins/junit_tests_report/lib/junit_tests_report.rb
This removes the debug print in the junit along with scrubbing more xml escaped characters in junit test names.
> removed debug print in junit and expanded xml escaped characters in junit test names

- plugins/gcov/gcov.rake
- plugins/gcov/lib/gcov.rb
- plugins/gcov/lib/gcov_constants.rb
Two changes for gcov report:
- Regular expression should looks like this:
\bunity.c\b|\bcmock.c\b|\bcexception.c\b
to match exact source files with this names not sources with substring contains these words.
Previous expression:
unity|cmock|cexcpetion.c
cause removing files from GCOV: CODE COVERAGE SUMMARY when the source file contains 'unity' or 'cmock' substring in its name.
- UnityHelper.c file is not filtered in report_per_file_coverage_results() method what cause 'build/gcov/out/UnityHelper.gcno:no functions found' message in GCOV: CODE COVERAGE SUMMARY
The same issue is for bullseye, but unfortunately I do not have a licence to this tool to test these changes.
> Gcov fix code coverage summary

- lib/ceedling/tasks_tests.rake
As mentioned in #424 test:all should always run all tests even if nothing changed in sources.
TEST_SYM, and force_run => true are default options for setup_and_invoke() method.
> Restore run tests for test:all task

- lib/ceedling/test_invoker.rb
Project config_hash can be overwritten in convert_libraries_to_arguments() because lib_args works on original config_hash.
project.yml won't match to input.yml in @project_config_manager.process_test_config_change even if nothing has changed in the project.yml
Steps to reproduce:
1. Add to project.yml libraries section:
:libraries:
:placement: :end
:flag: "${1}"  # or "-L ${1}" for example
:common: &common_libraries []
:test:
- *common_libraries
:release:
- *common_libraries
2. Check @project_config_manager.config_hash[:libraries][:test][0] before call convert_libraries_to_arguments() - there is one empty element in the array
3. Check after convert_libraries_to_arguments() call - there is no empty element.
4. Overwritten config_hash is written to cache input.yml file
5. After next call …
> Fix convert_libraries_to_arguments() to not overwrite project config

- docs/CeedlingPacket.md
- lib/ceedling/constants.rb
- lib/ceedling/dependinator.rb
- lib/ceedling/objects.yml
- lib/ceedling/preprocessinator.rb
- lib/ceedling/project_config_manager.rb
- lib/ceedling/rules_tests.rake
- lib/ceedling/task_invoker.rb
- lib/ceedling/test_invoker.rb
- plugins/gcov/gcov.rake
- plugins/gcov/lib/gcov.rb
- plugins/gcov/lib/gcov_constants.rb
This Pull Request fixing issues related to compilation procedure for changed preprocessor definitions for tests.
- Invoke_test_preprocessed_files() and invoke_test_mocks() were called before processing preprocessor definitions changes. Changed defines must be checked separately before this methods.
- When defines have changed clear actions to correctly generate files. The issue was discovered for mocks, where header for mock is placed in cache. When prerequisites for mock are called then header from prerequisites is compared between current cached file and generated preprocessed file from `preprocess/files` directory.
When mock is generated once, and must be generated again because defines changes, method find_header_input_for_mock_file() to compare cache and preprocessed file for rule …
> Preprocessor defines for tests fixes

- assets/project_with_guts_gcov_abortonuncovered.yml
- assets/uncovered_example_file.c
- plugins/gcov/README.md
- plugins/gcov/lib/gcov.rb
- spec/gcov/gcov_deployment_spec.rb
- spec/gcov/gcov_test_cases_spec.rb
This allows CI to fail if any files are detected that do not have any gcov coverage info (which would render the coverage report not very reliable).
> Implement an abort-on-uncovered option to gcov

- lib/ceedling/generator_test_results.rb
This PR addresses two issues:
- unity test time is not defined properly when there are a message in the string and `elements[2]` does not contain the time;
- regex does not match the time correctly if the string contains braces.
> Fix test time matching in generator_test_results.rb

- lib/ceedling/defaults.rb
It is standard practice to define CC and friends
via the environment
* CC, CCLD, AS
Similarly, the environment usually defines CFLAGS & LDFLAGS
& ASFLAGS & LDLIBS to use, e.g. when enabling compile-time
hardening. Ceedling shouldn't ignore those either.
This also means that '-w' (to disable all warnings) should
be removed, as otherwise having them in the environment,
in particular as part of ${CC} doesn't work. I don't believe
it's good practice to disable all warnings anyway.
These changes also allows for easy cross-compilation, as cross
compilation environments typically set all those variables to
do the right thing.
Signed-off-by: André Draszik <git@andred.net>
> defaults: allow configuring gcc and friends via environment

- README.md
Without initializing the submodules, we won't be able to test the gem.
Fixes issue #472.
> Mention git submodule in README.md

- lib/ceedling/file_wrapper.rb
Ruby 2.7 has deprecated the use of a Hash as the last argument to its
functions. A simple solution is just to add the splat to the hash or
remove curly braces
> Fix deprecation warning

- plugins/gcov/lib/gcov.rb
Update to allow the configuration tag "gcov_uncovered_ignore_list" to support folders, including glob. It searches in all entries for files, even if the informed value was a folder. Finally, an array with all the files found within the gcov_uncovered_ignore_list to be used on the ignore analysis.
> Update to allow folder on GCOV uncovered ignore list

- lib/ceedling/preprocessinator.rb
- lib/ceedling/preprocessinator_helper.rb
- lib/ceedling/test_includes_extractor.rb
- lib/ceedling/test_invoker.rb
This pull request implements an automatic method to recognize .c files included to the test module. Once this .c file is included the preprocessor recognize and remove the module from object lists in order to avoid duplicate definition error. 
It allows the usage of #include for source files, procedure used to have access to private function and variables when unit testing.
> Added method to remove include ".c" file from objects linker list.

- lib/ceedling/project_config_manager.rb
- lib/ceedling/test_invoker.rb
- lib/ceedling/test_invoker_helper.rb
- Avoid situation where force_build file has the same timestamp like target file and rake task target is not rebuilt.
- Remove duplication of rake task used in tests.
Details in the commit messages.
> Fix rebuild files after changed defines

- docs/CeedlingPacket.md
- lib/ceedling/configurator.rb
Instead of using an array of imports, you can use hashes so that certain imports can be replaced by option files.
Not sure what other use cases there might be for this, but in my case, I was having to use 2 separate .ymls for two different types of test runs: host and simulator. I would have preferred that it defaults to the host without any "option:" or "project:" command line arguments. Unfortunately, there are certain things that need to be removed from the host configuration, to make the simulator configuration run correctly. This isn't possible when the host configuration uses the overall project.yml.
My solution to the problem was to change the :import: section of the project.yml to hashes so that the base configuration imports can be replaced by name in the option/project specific …
> Allow ability to specify keys for imports

- assets/auto_link_deep_dependencies/src/a.c
- assets/auto_link_deep_dependencies/src/b.c
- assets/auto_link_deep_dependencies/src/c.c
- assets/auto_link_deep_dependencies/src/internal_inc/a.h
- assets/auto_link_deep_dependencies/src/internal_inc/b.h
- assets/auto_link_deep_dependencies/src/internal_inc/c.h
- assets/auto_link_deep_dependencies/src/internal_inc/never_compiled.h
- assets/auto_link_deep_dependencies/src/never_compiled.c
- assets/auto_link_deep_dependencies/test/test_a.c
- assets/auto_link_deep_dependencies/test/test_b.c
- assets/auto_link_deep_dependencies/test/test_c.c
- lib/ceedling/constants.rb
- lib/ceedling/objects.yml
- lib/ceedling/preprocessinator_includes_handler.rb
- spec/preprocessinator_includes_handler_spec.rb
- spec/spec_system_helper.rb
- spec/system/deployment_spec.rb
This PR helps to solve few issues related to `auto_link_deep_dependencies` feature. I also made small refactor in `extract_includes_helper(...)` method.
The `auto_link_deep_dependencies` is really powerfull feature, but I have noticed that something was wrong when I was trying to use mocks :). The same issue exists for `temp_sensor` example, so I have been able to easily debug the problem.
It is easier to explain what I did in small steps:
- Incorrect mock includes handling can be noticed for `list` variable at the end of call `extract_includes(filepath)` method:
`list` variable from `extract_includes(filepath)` for master branch on the first run `ceedling test:AdcConductor`:
```
[0]:'/home/x/repos/example/vendor/ceedling/vendor/unity/src/unity.h'
[1]:'test/support/UnityHelper.h' …
```
> Includes helper fixes

- assets/test_example_with_parameterized_tests.c
- docs/CeedlingPacket.md
- lib/ceedling/configurator.rb
- lib/ceedling/defaults.rb
- lib/ceedling/objects.yml
- lib/ceedling/preprocessinator.rb
- lib/ceedling/preprocessinator_extractor.rb
- lib/ceedling/preprocessinator_file_handler.rb
- spec/preprocessinator_extractor_spec.rb
- spec/spec_system_helper.rb
- spec/system/deployment_spec.rb
This PR is continuation of #445, but after #491 many of changes are already implemented and this PR becomes more straight forward.
Unity allows to use parameterized tests by TEST_CASE() and TEST_RANGE() macros.
After standard preprocessing when `use_test_preprocessor` option is enabled then macros are fully expanded to C code, so input file in the Unity test runner can not parse special macros and correctly handle parameterized tests.
Luckily in gcc compiler we can use `-fdirectives-only` flag to expand the conditional preprocessor, directives and leave the other content of the file untouched.
For example file with the parameterized tests can looks like below:
```c
#include "unity.h"
#define TEST_CASE(...)
#define TEST_RANGE(...)
void setUp(void) {}
void tearDown(void) {}
TEST_CASE(25) …
```
> Add preprocessing feature to expand only directives and conditional statements

- assets/test_example_file_unity_printf.c
- assets/tests_with_defines/src/adc_hardware.c
- assets/tests_with_defines/src/adc_hardware.h
- assets/tests_with_defines/src/adc_hardware_configurator.c
- assets/tests_with_defines/src/adc_hardware_configurator.h
- assets/tests_with_defines/test/test_adc_hardware.c
- assets/tests_with_defines/test/test_adc_hardware_special.c
- docs/CeedlingPacket.md
- lib/ceedling/configurator_builder.rb
- lib/ceedling/configurator_setup.rb
- lib/ceedling/test_invoker.rb
- spec/spec_system_helper.rb
- spec/system/deployment_spec.rb
- Vendor defines shouldn't be removed for test with specified "test_name" defines.
- Test for PR #430
- Add `--local` flag for `bundle config set` command. Without this flag `BUNDLE_PATH` variable from user config file, for ex. the `~/.bundle/config` was overwritten after run `bundle exec rake `.
> Add vendor defines for tests with specific defines

- plugins/gcov/README.md
- plugins/gcov/config/defaults.yml
- plugins/gcov/lib/gcovr_reportinator.rb
- plugins/gcov/lib/reportgenerator_reportinator.rb
1. Moved the gcov command line arguments to defaults.yml so they may be overridden in project.yml.
2. Pass "settings:createSubdirectoryForAllReportTypes=true" to Report Generator when multiple reports are specified in project.yml.
3. Skip running gcov on .gcno files that do not have a matching .gcda file.
4. Added gcov:report_generator:gcov_exclude as an optional list of regular expressions to avoid running gcov on files that match these exclude filters.
5. Added gcov:report_generator:num_parallel_threads to tell Report Generator to use the specified number of threads.
6. Added gcov:report_generator:gcov_executable to specify a particular gcov to call when generating .gcov files.
7. Added gcov:report_generator:custom_args as an optional list of command line arguments to pass to Report …
> gcov plugin - Additional Report Generator Configuration Options

- .github/workflows/main.yml
Hi!
- I noticed the Github Actions starts failing on the current master branch. I think it is caused by some conflicts with system gems.
https://github.com/CezaryGapinski/Ceedling/runs/2007065955?check_suite_focus=true
```
/var/lib/gems/2.5.0/gems/did_you_mean-1.5.0/lib/did_you_mean/version.rb:2: warning: previous definition of VERSION was here
/usr/lib/ruby/vendor_ruby/did_you_mean/jaro_winkler.rb:63: warning: already initialized constant DidYouMean::JaroWinkler::WEIGHT
/var/lib/gems/2.5.0/gems/did_you_mean-1.5.0/lib/did_you_mean/jaro_winkler.rb:63: warning: previous definition of WEIGHT was here
/usr/lib/ruby/vendor_ruby/did_you_mean/jaro_winkler.rb:64: warning: already initialized constant DidYouMean::JaroWinkler::THRESHOLD
/var/lib/gems/2.5.0/gems/did_you_mean-1.5.0/lib/did_you_mean/ja …
```
> Use local gem and multiple ruby versions in Github Actions

- plugins/module_generator/README.md
The actual example in the readme isn't working, because of missing subsection array.
Added subsection array like ":src" or ":tst" in the example.
> Changed "Include" section in module_generator readme

- plugins/module_generator/README.md
- plugins/module_generator/lib/module_generator.rb
Hello,
I had the problem, that the recently added "#ifdef TEST" in the testfile didn't work, because I used the define "TEST" for other purposes. This is why I made the define customizable via the project.yml in ceedling. With this, you can use your own define (in my case "CEEDLING_TEST").
I hope its useful :)
Related to Unity pull request: [ThrowTheSwitch/Unity#545](https://github.com/ThrowTheSwitch/Unity/pull/545)
> Test define customizable in via project.yml

- bin/ceedling
Running 'ceedling new project' or even 'ceedling version' in windows with version V0.31.0 is raising errors because ceedling was not able to find version.rb module. 
This fix is replacing the current relative path to this file in ceedling module, with the usage of the absolute folder based on the currently running file. With that, it is expected that independently where the user is running the ceedling build, the module will be always able to find the 'version.rb' as required
> Fixed issue with required Version.rb module on Windows

- lib/ceedling/preprocessinator_extractor.rb
> Fix encode problem in preprocessinator_extractor

- lib/ceedling/version.rb
Hi
I would like to propose fix for https://github.com/ThrowTheSwitch/Ceedling/issues/595, in which when we forgot to init submodules and update them we receive:
`
undefined method `exists?' for Ceedling::Version:Module
`
error.
In proposed solution, if we forgot to update unity, in the console we will see:
`
Can't collect data for vendor component: "UNITY" . 
Please check your setup.
`
I have hope that this fix will to suit your needs.
> Fix problem with exists? when vendor submodules are not initialized

- plugins/junit_tests_report/lib/junit_tests_report.rb
Hi
I would like to propose small fix to junit xml format which is generated for *:junit_tests_report:*
1. Surfire test
Current format is not compatible with schema as:
http://maven.apache.org/surefire/maven-surefire-plugin/xsd/surefire-test-report.xsd
The time generated by reporter and added to report file in time argument is failing as is not fitting to  pattern '(([0-9]{0,3},)*[0-9]{3}|[0-9]{0,3})*(\.[0-9]{0,3})
`
report_junit.xml:cvc-pattern-valid: Value '0.003235' is not facet-valid with respect to pattern '(([0-9]{0,3},)*[0-9]{3}|[0-9]{0,3})*(\.[0-9]{0,3})?' for type 'SUREFIRE_TIME'
`
2. Ant
- Add missing errors attribute under test suite node `report_junit.xml:cvc-complex-type.4: Attribute 'errors' must appear on element 'testsuite'.`
- Remove skipped attribute from test suites node …
> Fix the junit_test_reporter to fit Ant and Surfire test schema

- .github/workflows/main.yml
It seems as if the floating point number 3.0 gets automatically converted to 3, which results in the latest version of Ruby 3 getting selected (which is 3.1 at the moment).
The fix here is to put the number in single quotes, avoiding the conversion.
> Use Ruby 3.0 for Github CI

- lib/ceedling/configurator_builder.rb
- lib/ceedling/file_finder.rb
- lib/ceedling/file_path_utils.rb
- lib/ceedling/generator.rb
- lib/ceedling/generator_test_runner.rb
- lib/ceedling/rules_cmock.rake
- lib/ceedling/test_includes_extractor.rb
My current project has a very nested folder structure which forces us to use globs in the `:include:` section of our `project.yml` which in turn at some point caused the gcc-compile command to exceed the maximum command-line length. 
In order to fix this i would like to eliminate the need for globs while also allowing us to mock headers located in Subdirectories. 
This pull request allows ceedling to generate mocks for headers located in sub directories. (also requested by #358 )
This allows headers in sub directories to be mocked without using globs in the `:include:` section of the `project.yml`
The following use-cases would now be supported:
```C
#include "Subdir/Mock_Test.h"
#include "Mock_Test2.h"
#include "Subdir1/Subdir2/Mock_Test3.h"
```
- The FFF plugin's `setup_mocks()`-function …
> Add support for mock generation to match the original headers Subdirectory

- lib/ceedling/generator_test_results.rb
If the test result line ends with /r/n parser will not match the PASS criteria due to the $ in the regular expression.
Comping the line fixes the issue.
> Chomped output line before parsing test results.

- lib/ceedling/test_includes_extractor.rb
Fix the regex in extract_from_file function to proper parse
'# include' preprocessor directive.
The problem was mentioned under:
https://github.com/ThrowTheSwitch/Ceedling/issues/588
> Fixed issue 588 with space between # and include preprocessor directive

- plugins/gcov/lib/gcovr_reportinator.rb
Proposed solution for issue described in #641.
Disable running twice 4.2 gcovr when:
-  calls of  args_builder_cobertura /- args_builder_sonarqube / args_builder_json / args_builder_html functions does not update args.
- when Text Report is not set.
> Disable running twice gcov when only TEXT report enabled

- lib/ceedling/defaults.rb
- lib/ceedling/generator_test_results.rb
- lib/ceedling/test_invoker.rb
- plugins/json_tests_report/lib/json_tests_report.rb
- plugins/teamcity_tests_report/lib/teamcity_tests_report.rb
- plugins/xml_tests_report/lib/xml_tests_report.rb
This change affects how test file names are reported. The test file name is prepended with its path up to the project root, i.e. the location of project.yml
For example ``test_something.c`` becomes ``test/subfolder1/test_something.c``
**Motivation**
- Source trees are often organized into multiple subfolders, therefore using the same structure for the test files helps to keep sources and tests better connected. Adding the path to the report helps to quickly identify the test file in question.
- IDEs need the entire path to unambiguously identify a test file so it can be opened it in case of a failed test. The Eclipse Unit Testing Framework has been observed picking the wrong file when clicking on a failure report, opening the prepocessed file with the same name but located in the cache …
> Report test file name with subfolders

- docs/CeedlingPacket.md
```
/usr/local/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require': cannot load such file -- Ceedling (LoadError)
from /usr/local/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
from rakefile.rb:1:in `<top (required)>'
from /usr/local/bundle/gems/ceedling-0.31.1/bin/ceedling:322:in `load'
from /usr/local/bundle/gems/ceedling-0.31.1/bin/ceedling:322:in `<top (required)>'
from /usr/local/bundle/bin/ceedling:23:in `load'
from /usr/local/bundle/bin/ceedling:23:in `<main>'
```
> Loading ceedling module fails on Linux (not local)

- .github/workflows/main.yml
- bin/ceedling
- lib/ceedling/erb_wrapper.rb
- lib/ceedling/plugin_reportinator_helper.rb
- spec/spec_system_helper.rb
- spec/system/deployment_spec.rb
PR'st changes:
- [main.yml] Remove commented test run for ruby 3.2
- [ceedling] Fix issue with undeclared yaml_path variable
Fix undeclared yaml_path variable when user call:
ceedling upgrade <non_existing_project>
- Add trim_mode to ERB.new function as parameter specifier
Add test to cover check of upgrade function for non existing project
> Fix issue with undeclared yaml_path variable when calling ceedling upgrade on none existing project

- docs/CeedlingPacket.md
- lib/ceedling/defaults.rb
- lib/ceedling/generator.rb
- lib/ceedling/generator_test_results.rb
---
**FEATURE**
Add GDB support to collect SIGSEGV logs from tests which fails on x86 machines.
---
**PR includes**
Updated code
Updated README.md with new project configuration option.
---
**Short description**
During development of the unit tests for my previous project, I observed sometimes  the issues connected with Segmentation fault( SEGFAULT/ SIGSEGV ).
The Ceedling does not deliver us possibility to easily check, why, and which test is failing, and is not creating as we expect report.xml file. It is only failing with description:
```
ERROR: Test executable "test_add.out" failed.
> Produced no final test result counts in $stdout:
Segmentation fault (core dumped)
> And exited with status: [0] (count of failed tests).
> This is often a symptom of a bad memory access in source or test …
```
> Add possibility to collect backtrace using GDB for 'Segmenation fault' errors in n tests

- lib/ceedling/file_system_utils.rb
When using this tool to build release binaries, I found it was important to force a consistent order of files fed to the linker across machines.
> Account for different ordering of files when traversing filesystem

- bin/ceedling
- docs/CeedlingPacket.md
- lib/ceedling/configurator_builder.rb
- lib/ceedling/generator.rb
- lib/ceedling/objects.yml
- lib/ceedling/rules_tests.rake
- lib/ceedling/unity_utils.rb
- spec/spec_system_helper.rb
- spec/system/deployment_spec.rb
---
**FEATURE**
Add possibility to execute single or multiple tests cases from one test file, or exclude some of test cases from test execution.
Base on request: #330 , #243
---
**PR includes**
Updated code :
-  Added new class UnityUtils.rb. (no code style issues - tested via rubocop)
- Updated implementation of configurator_builder.rb
- Updated implementation of generatior.rb
- Updated implementation or rules_tests.rb
Updated CeedlingPacket.md with new ceedling functionality.
Added 5 UT to cover new functionality. ( rubocop describe problems with to long name description)
---
**Short description**
This PR contains extension which enable execution of:
- one 
- or multiple tests
- or non if the passed test case name is not fitting passed by end user parameter after colon
Referring to #330 …
> Feature - add functionality to run single or multiple tests from one or multiple test files 

- plugins/html_tests_report/README.md
- plugins/html_tests_report/lib/html_tests_report.rb
Hello!
I made a html_tests_report plugin based on xml_tests_report to generate pretty html report of tests.
Colorful output of Summary, Failed, Ignored and Successes tests tables. It also hide long messages to spoiler.
I think it is really useful and easy to use! In future, if required, there are might be more settings: colors, table order, columns or max length of message.
There is an example of generated page:
> Add html_tests_report plugin

- lib/ceedling/defaults.rb
When not having GDB installed and even if i put the `use_backtrace_gdb_reporter: FALSE` the path for GDB is checked. Since I do not want to define `tools: backtrace...` in my project yml, since I do not use it at the moment, it would be fair to make it optional (and hence removing the path check by default). Optional helps by not having to have gdb installed in CI, but workaround I assume is to define `tools: backtrace_settings: optional: TRUE` in `project.yml` 
Found in https://github.com/ThrowTheSwitch/Ceedling/pull/739#issuecomment-1545319491
> Default make the backtrace tool as optional

- docs/CeedlingUpgrade.md
Fixed typo in step 2 of the update steps. the documents originally read "Udpate" which has been changed to "Update"
> Fixed typo in update steps

- plugins/bullseye/lib/bullseye.rb
Hi,
I've detected the Bullseye plugin was not working because the changes introduced by #265. I fixed it just doing the same change it was done for the gcov plugin.
BR,
Carlos Carrizosa
> Fix Bullseye plugin: configure project_test_build_output_c_path

- bin/mixinator.rb
On recent pre-release versions of Ceedling, I'm getting the following error when trying to use mixins from command line:
```shell
🧨 EXCEPTION: no implicit conversion of Hash into String
🚧 Loaded project configuration at default location using ./project.yml
Backtrace ==>
/home/alejo/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/ceedling-0.32.0/bin/path_validator.rb:51:in `extname': no implicit conversion of Hash into String (TypeError)
/home/alejo/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/ceedling-0.32.0/bin/path_validator.rb:51:in `filepath?'
/home/alejo/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/ceedling-0.32.0/bin/mixinator.rb:86:in `block in assemble_mixins'
/home/alejo/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/ceedling-0.32.0/bin/mixinator.rb:84:in `uniq!' …
```
> Fix filepath expansion in assemble_mixins().

- bin/projectinator.rb
On recent pre-release versions of Ceedling, command line mixins are not being merged.
> Fix command line mixins merging.

- plugins/valgrind/README.md
- plugins/valgrind/config/defaults_valgrind.rb
- plugins/valgrind/lib/valgrind.rb
- plugins/valgrind/lib/valgrind_constants.rb
- plugins/valgrind/valgrind.rake
This PR is the second attempt at adding the Valgrind plugin to Ceedling. The plugin implementation closely follows the Gcov plugin.
The `test/ceedling_0_32_rc` branch was deleted and v1.0.0 was released without these changes. I assume these changes were missed during the merging of the various v1.0.0 changes into the master branch. No changes were made from the previous PR (#807).
Fixes #277.
> Add Valgrind plugin

- bin/projectinator.rb
- lib/ceedling/configurator.rb
- lib/ceedling/constants.rb
- lib/ceedling/file_path_utils.rb
- lib/ceedling/generator_helper.rb
- lib/ceedling/generator_test_results.rb
- lib/ceedling/include_pathinator.rb
- lib/ceedling/objects.yml
- lib/ceedling/parsing_parcels.rb
- lib/ceedling/preprocessinator_extractor.rb
- lib/ceedling/test_context_extractor.rb
- lib/ceedling/test_invoker_helper.rb
- lib/ceedling/tool_executor.rb
- lib/ceedling/tool_validator.rb
- spec/parsing_parcels_spec.rb
- spec/preprocessinator_extractor_spec.rb
- spec/test_context_extractor_spec.rb
Fix parsing issues with comment handling. (#978, #981, #985)
> Fix parsing issue

- lib/ceedling/preprocessinator_extractor.rb
- lib/ceedling/preprocessinator_file_handler.rb
- spec/preprocessinator_extractor_spec.rb
The best solution was both the simplest and most robust — comparing absolute file paths when deciding which sections of a preprocess file to extract.
- Comment documentation clarified and expanded
- Test cases expanded to better cover desired extraction and content to be ignored.
All tests pass and new prerelease is a avaialble.
> 1.0.1 bug fix for preprocessing extraction
