ThrowTheSwitch/Ceedling

lib/ceedling/tasks_base.rake

Casing of module and constant was wrong

Fix 'rake version' not working

---

lib/ceedling/tasks_base.rake

I don't know if you can easy sort it otherwise.. And I wonder why it's a list of dicts and not a dict ?

Show environment sorted

---

plugins/junit_tests_report/lib/junit_tests_report.rb

Tested compatible with Atlassian Bamboo JUnit Parser plugin

Add plugin to generate test report in JUnit format

---

.travis.yml

To keep us honest and make sure that ceedling is working properly, I've updated the Travis matrix to run the given ceedling examples.

Now running ceedling examples as part of travis CI.

---

lib/ceedling/target_loader.rb
spec/target_loader_spec.rb

Another commit for internal testing.

Added tests for TargetLoader

---

spec/file_finder_helper_spec.rb

This commit is one of many I hope to do to add more testing to the interworkings of Ceedling and find potential issues and prevent new ones from showing up.

Added tests for file_finder_helper

---

lib/ceedling/reportinator.rb
spec/reportinator_spec.rb

More tests. Also added documentation since it was really easy to make for this class.

Added tests for reportinator and some documentation for it also

---

lib/ceedling/generator_test_results_sanity_checker.rb
spec/generator_test_results_sanity_checker_spec.rb

Another commit for internal testing. Also added additional checks for nil/empty reports

Added tests for generator_test_results_sanity_checker.rb

---

lib/ceedling/generator_test_results.rb
spec/generator_test_results_spec.rb
spec/support/test_example.fail
spec/support/test_example.pass
spec/support/test_example_empty.pass
spec/support/test_example_ignore.pass
spec/support/test_example_mangled.pass

More tests and also handles an issue with mangled output from running test I've been starting to see [as shown here](https://travis-ci.org/dpostorivo/ceedling_fprintf_stderr_error/jobs/228903750).

Added tests for GeneratorTestResults and added a failsafe for parsing mangled output

---

lib/ceedling/build_invoker_utils.rb
spec/build_invoker_utils_spec.rb

More tests. Also added basic documentation since it is just one function.

Added tests to BuildInvokerUtils and documentation

---

lib/ceedling/system_utils.rb
spec/system_utils_spec.rb

Added tests and docs for system_utils.rb

---

lib/ceedling/tool_executor_helper.rb
spec/tool_executor_helper_spec.rb

More documentation and testing.

Added testing and documentation for tool_executor_helper_spec

---

lib/ceedling/project_file_loader.rb

The proposed change allows to specify via the CEEDLING_MIXIN_PROJECT_FILES environment variable, multiple yml files which will be merged with the project file to construct the final config hash.

Enable mixin of additional yml project files

---

plugins/command_hooks/lib/command_hooks.rb

fix(command_hooks) support command args

---

lib/ceedling/file_finder.rb

This is an attempt to address the thread safety issue in #191. It seems that the issues were a result of trying to find the same set of files twice using the file finder and the file finder helper. I'm relatively sure the configurator is actually where the thread safety issues are since when this bug does happen, the configurator objects are screwed up and this and the helper work like they are suppose to. 
After this mutex was added no issues were observed following the steps of #191.

Added Mutex to file search due to observed collisions

---

bin/ceedling
lib/ceedling/configurator_setup.rb
plugins/gcov/gcov.rake

#247 always create build root

---

lib/ceedling/task_invoker.rb
lib/ceedling/test_invoker.rb

Use `par_map` for building tests as well as releases.

Build tests in parallel

---

lib/ceedling/tool_executor.rb
plugins/command_hooks/README.md
plugins/command_hooks/lib/command_hooks.rb

- Removed double named hook in doc.
- command_hooks document fixup.
- build_command_line called with correct arguments (AFAIK)

Fixed the command_hook plugin.

---

assets/project_as_gem.yml
assets/project_with_guts.yml
assets/project_with_guts_gcov.yml
examples/blinky/project.yml

commmon -> common

---

docs/CeedlingPacket.md

This attempts to address #232 by better documenting how to get started with Ceedling once it is installed.

Add documentation on how to integrate Ceedling after installing it

---

Gemfile
Gemfile.lock
ceedling.gemspec

Bumps minimum rake version based on #214

Update minimum rake version based on issue #214

---

lib/ceedling/configurator.rb
spec/spec_system_helper.rb
spec/system/deployment_spec.rb

This fixes #208 and is a replacement for fix #215 which removes the default. Also added tests to guarantee this feature works out of the box.

plugin deep merge usability change

---

README.md

This hopes to add documentation to help in installing bundler as pointed out in issue #326 .

Add additional bundler instructions in README

---

lib/ceedling/configurator.rb

Fixes #63 by making sure every path list is an array before flatting.

Sanatize incoming path list from yml

---

plugins/module_generator/lib/module_generator.rb

PR for issue https://github.com/ThrowTheSwitch/Ceedling/issues/395

Added a the :boilerplate_files: option to module_generator.rb

---

docs/CeedlingPacket.md

Description about import feature for project files (PR #128).

Update documentation for import option

---

plugins/gcov/gcov.rake

Pull request to resolve issue #414 .

Resolve Issue #414 where gcov XML Report Generation is Broken

---

README.md

I guess we are testing some Ceedling's internals not Cmock's

Fix mention about Run all Ceedling library tests

---

plugins/compile_commands_json/README.md

Initial attempt to add a bit more context.

Initial attempt at adding more context

---

lib/ceedling/cacheinator_helper.rb

This PR helps to solve issue #442

Fix for reduced gcov coverage data on first run

---

plugins/dependencies/lib/dependencies.rb

Ironically managed to create a test scenario that ultimately did the opposite of what was intended.
I've tested this change with a few different commits and it looks like it is doing the right thing.

Fix inverted dependency logic

---

lib/ceedling/preprocessinator_includes_handler.rb
lib/ceedling/project_config_manager.rb
spec/preprocessinator_includes_handler_spec.rb

Fix regex to handle includes with similar names (#525).

Fix test files with similar include names

---

docs/CeedlingPacket.md

Took me a bit to figure out how to do it with the gem version. Thought I best document it here so others can cut the corner.
I hope this is the intended way to add my own rake tasks. Otherwise the examples might need an update.
Thanks for the awesome tool :)

Add documentation for custom rake tasks

---

assets/example_file_call.c
assets/example_file_call.h
assets/test_example_file_with_mock.c
lib/ceedling/defaults.rb
lib/ceedling/preprocessinator_includes_handler.rb
spec/preprocessinator_includes_handler_spec.rb
spec/spec_system_helper.rb
spec/system/deployment_spec.rb

Handful of useful fixes for includes preprocessinator handler I've stumbled upon during using ceedling.

Preprocessinator includes handler fixes

---

ceedling.gemspec
lib/ceedling/version.rb
plugins/gcov/lib/gcovr_reportinator.rb
spec/gcov/gcov_deployment_spec.rb

Support newer rake.
Bump Version.

Grab latest dependencies.

---

plugins/gcov/README.md

added known issues section for empty gcovr

---

plugins/compile_commands_json/lib/compile_commands_json.rb

Adding size check before parsing file. Previously this would throw an unhandled parse error.

Adding a zero size check to json fie

---

.github/workflows/main.yml
assets/test_example_file_sigsegv.c
spec/spec_system_helper.rb
spec/system/deployment_spec.rb

Add to assets test_example_file_sigsegv.c sigsegv test file
Update main.yml with install gdb install dependency.

[UT] Add unit tests to check :use_backtrace_gdb_reporter option

---

.rubocop.yml
bin/ceedling
lib/ceedling/build_invoker_utils.rb
lib/ceedling/configurator_builder.rb
lib/ceedling/configurator_validator.rb
lib/ceedling/file_finder.rb
lib/ceedling/flaginator.rb
lib/ceedling/target_loader.rb
lib/ceedling/tool_executor.rb
plugins/dependencies/lib/dependencies.rb
plugins/gcov/gcov.rake
spec/build_invoker_utils_spec.rb
spec/spec_system_helper.rb
spec/system/deployment_spec.rb

Added more lint fixes found with rubocop and the rubocop.yml from unity. There are a handful of lint issues highlighted that should be tackled later as it affects logic (like assignment in if statement, unused variables).

More lint fixes + add rubocop.yml from unity

---

docs/CeedlingCustomPlugins.md
docs/CeedlingPacket.md

This closes #680.
The idea is to receive feedback to improve this doc so the plugin making process is well documented.

Document plugin making

---

plugins/beep/README.md
plugins/beep/config/defaults.yml
plugins/beep/lib/beep.rb
plugins/beep/lib/beep_tools.rb

The proposed solution mentioned [here](https://github.com/ThrowTheSwitch/Ceedling/issues/459#issuecomment-1518832629).

Fix beep plugin

---

.gitignore
assets/project_as_gem.yml
assets/project_with_guts.yml
assets/project_with_guts_gcov.yml
examples/temp_sensor/project.yml
lib/ceedling/configurator.rb
lib/ceedling/configurator_plugins.rb
lib/ceedling/configurator_setup.rb
lib/ceedling/file_finder_helper.rb
lib/ceedling/plugin.rb
lib/ceedling/setupinator.rb
lib/ceedling/tasks_base.rake
plugins/module_generator/README.md
plugins/module_generator/Rakefile
plugins/module_generator/assets/stubby1.h
plugins/module_generator/assets/stubby2.h
plugins/module_generator/config/module_generator.yml
plugins/module_generator/example/project.yml
plugins/module_generator/lib/module_generator.rb
plugins/module_generator/module_generator.rake

Clean up bugs in module generator.
Backfilled tests for module generator.
Beefed documentation for module generator.

Dev/0 32/module generator updates

---

plugins/module_generator/README.md

Add documentation to commit fixing #949

doc: Module generator alternative path

---

assets/project.yml
examples/temp_sensor/project.yml
lib/ceedling/file_finder_helper.rb
lib/ceedling/file_path_collection_utils.rb
plugins/module_generator/README.md
plugins/module_generator/Rakefile
plugins/module_generator/config/module_generator.yml
plugins/module_generator/example/project.yml
plugins/module_generator/lib/module_generator.rb

- 🐛 Fixes #996 by making handling more consistent, and erring on bad data.
- 📝 New paths are explicitly discussed in documentation now.

Updates to module_generator path handling to be more repeatable.
